server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false # 开发时关闭缓存,不然没法看到实时页面
      mode: HTML # 用非严格的 HTML
      encoding: UTF-8
      servlet:
        content-type: text/html
    mvc:
      static-path-pattern: /static/**



# MyBatis
mybatis:
  configLocation: classpath:config/mybatis-config.xml
  type-aliases-package: com.zyx.model
  mapper-locations: classpath:mapper/*.xml



